import assert from 'node:assert/strict';
import http from 'node:http';
import { spawn } from 'node:child_process';
import { chromium } from 'playwright-core';
import { createHandler } from '../api/chat.js';

let payload;
const handler = createHandler({ env: { AI_CHAT_ENABLED: 'true', ARK_API_KEY: 'test-only' }, fetcher: async (url, options) => {
  assert.equal(url, 'https://ark.cn-beijing.volces.com/api/v3/responses');
  payload = JSON.parse(options.body);
  return { ok: true, json: async () => ({ output: [{ type: 'message', content: [{ type: 'output_text', text: JSON.stringify({ answer: 'Mock explanation', suggestions: ['追问一？', '追问二？', '追问三？'] }) }] }] }) };
} });
const mock = http.createServer(handler);
await new Promise(resolve => mock.listen(0, '127.0.0.1', resolve));
const base = `http://127.0.0.1:${mock.address().port}`;
try {
  const result = await fetch(base, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: 'Explain', context: { english: 'Excuse me!' }, history: [] }) });
  assert.equal(result.status, 200); assert.equal((await result.json()).answer, 'Mock explanation');
  assert.equal(payload.store, false); assert.equal(payload.model, 'doubao-seed-2-0-lite-260428');
  const teachingRules = payload.input[0].content;
  assert.match(teachingRules, /中文母语学习者/);
  assert.match(teachingRules, /不要逐词罗列词性/);
  assert.match(teachingRules, /直接回答这个问题，不重新分析整句/);
  assert.match(teachingRules, /不编造背景/);
  assert.match(teachingRules, /没有修改课程、成绩或学习记录的权限/);
  assert.doesNotMatch(teachingRules, /默认用两到四句或最多三个要点/);
  assert.equal((await fetch(base)).status, 405);
  assert.equal((await fetch(base, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })).status, 400);
} finally { await new Promise(resolve => mock.close(resolve)); }

const child = spawn(process.execPath, ['scripts/dev-server.mjs'], { env: { ...process.env, PORT: '4188', ARK_API_KEY: '', AI_CHAT_ENABLED: 'false' }, stdio: ['ignore', 'pipe', 'pipe'] });
let browser;
try {
  const url = await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(Error('Server timeout')), 10000);
    child.stdout.on('data', data => { const match = String(data).match(/http:\/\/127\.0\.0\.1:\d+/); if (match) { clearTimeout(timer); resolve(match[0]); } });
    child.on('error', reject);
  });
  assert.equal((await fetch(`${url}/.env.local`)).status, 404);
  assert.equal((await fetch(`${url}/api/chat`, { method: 'POST' })).status, 503);
  browser = await chromium.launch({ headless: true, executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
  for (const width of [1280, 430]) {
    const page = await browser.newPage({ viewport: { width, height: 932 } });
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.goto(url);
    await page.click('#openNce1Btn'); await page.click('.lesson-card[data-id="lesson-1"]'); await page.click('#startBtn');
    await page.click('.ask-ai-entry');
    assert.equal(await page.locator('.tutor-dialog').evaluate(el => el.open), true);
    assert.equal(await page.locator('.tutor-suggestions button').first().textContent(), '帮我分析这句话');
    assert.equal(await page.locator('.tutor-context-english').textContent(), 'Excuse me!');
    assert.equal(await page.locator('.tutor-form textarea').evaluate(el => el === document.activeElement), width > 660);
    await page.locator('.tutor-form textarea').click();
    assert.equal(await page.locator('.tutor-form textarea').evaluate(el => el === document.activeElement), true);
    await page.click('.tutor-header button');
    await page.click('.ask-ai-entry');
    assert.equal(await page.locator('.tutor-form textarea').evaluate(el => el === document.activeElement), width > 660);
    await page.evaluate(() => {
      const original = speechSynthesis.getVoices;
      const us = { lang: 'en-US', localService: true };
      const gb = { lang: 'en-GB', localService: true };
      speechSynthesis.getVoices = () => [us, gb];
      const utterance = configureEnglishSpeech({});
      if (utterance.voice !== gb || utterance.lang !== 'en-GB' || utterance.rate !== 0.8) throw Error('British voice selection failed');
      speechSynthesis.getVoices = () => [];
      if (configureEnglishSpeech({}).lang !== 'en-GB') throw Error('British fallback failed');
      speechSynthesis.getVoices = original;
      if (britishPhoneticFor('coat') !== '/kəʊt/' || britishPhoneticFor("can't") !== '/kɑːnt/') throw Error('British IPA failed');
      Object.defineProperty(navigator, 'audioSession', { configurable: true, value: { type: 'auto' } });
      prepareMediaPlayback();
      if (navigator.audioSession.type !== 'playback') throw Error('Playback session not selected');
      Object.defineProperty(navigator, 'audioSession', { configurable: true, get() { throw Error('Unsupported'); } });
      prepareMediaPlayback();
      delete navigator.audioSession;
      prepareMediaPlayback();
    });
    let chatCalls = 0;
    const histories = [];
    await page.route('**/api/chat', async route => {
      chatCalls++;
      const body = route.request().postDataJSON(); assert.equal(body.context.english, 'Excuse me!'); histories.push(body.history);
      await route.fulfill({ json: { answer: '**重点**\n\n- 主干\n- 补充说明\n\n> 两句合并\n\n<script>not HTML</script>\n\n[unsafe](javascript:alert(1))\n\n![image](https://example.com/image.png)', suggestions: ['这里为什么用这个词？', '还有哪些使用场景？', '这个表达礼貌吗？'] } });
    });
    await page.locator('.tutor-form textarea').fill('Explain this');
    await page.click('.tutor-form button');
    await page.locator('.tutor-message[data-role=assistant]').waitFor();
    await page.locator('.tutor-followups button').first().waitFor();
    assert.equal(await page.locator('.tutor-followups button').count(), 3);
    assert.equal(chatCalls, 1);
    assert.equal(await page.locator('.tutor-messages script').count(), 0);
    assert.equal(await page.locator('.tutor-message[data-role=assistant] strong').textContent(), '重点');
    assert.equal(await page.locator('.tutor-message[data-role=assistant] li').count(), 2);
    assert.equal(await page.locator('.tutor-message[data-role=assistant] blockquote').count(), 1);
    assert.equal(await page.locator('.tutor-message[data-role=assistant] a, .tutor-message[data-role=assistant] img').count(), 0);
    await page.evaluate(async () => {
      const { renderTutorMarkdown } = await import('/tutor-markdown.js');
      const node = document.createElement('div');
      for (const text of ['**主', '**主干**\n\n> 原句', '**主干**\n\n> 原句\n> → 合并']) renderTutorMarkdown(node, text);
      if (node.querySelector('strong')?.textContent !== '主干' || !node.querySelector('blockquote')) throw Error('Stream formatting failed');
    });
    const before = await page.locator('#sentenceOrder').textContent();
    await page.locator('.tutor-form textarea').press('Enter');
    assert.equal(await page.locator('#sentenceOrder').textContent(), before);
    const bounds = await page.locator('.tutor-dialog').boundingBox(); assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= width);
    await page.screenshot({ path: `reports/ai-chat-${width}.png` });
    await page.locator('.tutor-followups button').first().click();
    await page.waitForFunction(() => document.querySelectorAll('.tutor-message[data-role=user]').length === 2 && !document.querySelector('.tutor-form button').disabled);
    assert.equal(chatCalls, 2);
    assert.equal(await page.locator('.tutor-followups').count(), 1);
    assert.equal(await page.locator('.tutor-followups button').count(), 3);
    assert.equal(await page.locator('.tutor-message[data-role=user]').last().evaluate(el => el.firstChild.textContent), '这里为什么用这个词？');
    assert.equal(histories[1].length, 2);
    await page.click('.tutor-header button[aria-label="关闭"]');
    await page.click('.ask-ai-entry');
    assert.equal(await page.locator('.tutor-message[data-role=user]').count(), 2);
    await page.locator('.tutor-form textarea').fill('尚未发送的草稿');
    await page.locator('.tutor-edit-question').last().click();
    assert.equal(await page.locator('.tutor-form textarea').inputValue(), '这里为什么用这个词？');
    await page.locator('.tutor-edit-notice button').click();
    assert.equal(await page.locator('.tutor-form textarea').inputValue(), '尚未发送的草稿');
    assert.equal(chatCalls, 2);
    await page.locator('.tutor-edit-question').last().click();
    await page.locator('.tutor-form textarea').fill('修改后的局部问题');
    await page.locator('.tutor-form button').click();
    await page.waitForFunction(() => !document.querySelector('.tutor-form button').disabled);
    assert.equal(chatCalls, 3);
    assert.equal(histories[2].length, 2);
    assert.equal(histories[2][0].content, 'Explain this');
    assert.equal(await page.locator('.tutor-message[data-role=user]').count(), 2);
    await page.locator('.tutor-edit-question').first().click();
    await page.locator('.tutor-form textarea').fill('重写第一个问题');
    await page.locator('.tutor-form button').click();
    await page.waitForFunction(() => !document.querySelector('.tutor-form button').disabled);
    assert.equal(chatCalls, 4); assert.deepEqual(histories[3], []);
    assert.equal(await page.locator('.tutor-message[data-role=user]').count(), 1);
    assert.equal(await page.locator('.tutor-message[data-role=user]').first().evaluate(el => el.firstChild.textContent), '重写第一个问题');
    assert.equal(await page.locator('.tutor-followups').count(), 1);
    await page.click('.tutor-new-chat');
    assert.equal(await page.locator('.tutor-message, .tutor-followups').count(), 0);
    assert.equal(await page.locator('.tutor-context-english').textContent(), 'Excuse me!');
    assert.equal(await page.locator('.tutor-form textarea').evaluate(el => el === document.activeElement), false);
    await page.locator('.tutor-suggestions button').first().click();
    await page.waitForFunction(() => !document.querySelector('.tutor-form button').disabled);
    assert.deepEqual(histories[4], []);
    await page.click('.tutor-header button');
    assert.deepEqual(errors, []); await page.close();
  }
  console.log('AI API and desktop/mobile browser checks passed.');
} finally {
  await browser?.close();
  child.kill();
  if (child.exitCode === null) await new Promise(resolve => child.once('exit', resolve));
}
